version: "3.3"

services:
  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ecommerce
      - POSTGRES_AUTH_METHOD=md5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

  minio:
    image: quay.io/minio/minio:RELEASE.2023-06-09T07-32-12Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio@password123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    expose:
      - 9000
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data

  # ecommerce_backend:
  #   build:
  #     context: .
  #     dockerfile_inline: |
  #       FROM python:3.10
  #       WORKDIR /app
  #       COPY  requirements.txt /app/
  #       RUN pip install -r /app/requirements.txt
  #   command: ["flask", "run", "--host=0.0.0.0", "--port=8080"]
  #   volumes:
  #     - ./:/app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - minio
  #   ports:
  #     - 8080:8080