"""add field quantity to variants table

Revision ID: 53ba7767474f
Revises: 6197ad61d00c
Create Date: 2024-01-28 23:02:57.721741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53ba7767474f'
down_revision = '6197ad61d00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='account_role'),
               type_=sa.Enum('ADMIN', 'USER', name='account_role'),
               existing_nullable=False)

    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_column('warehouse_quantity')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'USER', name='account_role'),
               type_=postgresql.ENUM('ADMIN', 'USER', name='account_role'),
               existing_nullable=False)

    # ### end Alembic commands ###
