"""product_combination

Revision ID: 607968c6d0b6
Revises: e65d433702c9
Create Date: 2024-03-02 22:49:44.519702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607968c6d0b6'
down_revision = 'e65d433702c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_combinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combination_name', sa.String(length=255), nullable=False),
    sa.Column('warehouse_quantity', sa.Integer(), nullable=False),
    sa.Column('origin_price', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('origin_price > sale_price', name='check_origin_price_sale_price'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_combinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_combinations_combination_name'), ['combination_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_combinations_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('warehouse_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_quantity', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('product_combinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_combinations_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_combinations_combination_name'))

    op.drop_table('product_combinations')
    # ### end Alembic commands ###
