"""product_variant

Revision ID: e65d433702c9
Revises: 76de2cc9fbe7
Create Date: 2024-03-02 21:48:29.799281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65d433702c9'
down_revision = '76de2cc9fbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variant_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variant_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_options_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variant_options_product_id'), ['product_id'], unique=False)

    op.create_table('product_variant_option_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('product_variant_name_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_name_id'], ['product_variant_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variant_option_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_option_values_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant_option_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_option_values_value'))

    op.drop_table('product_variant_option_values')
    with op.batch_alter_table('product_variant_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_options_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_variant_options_name'))

    op.drop_table('product_variant_options')
    # ### end Alembic commands ###
